version: "3"
services:
  ip-addr-challenge:
    # build: .
    image: timmyb824/ip-addr-challenge:latest-arm64v8
    container_name: ip-addr-challenge
    ports:
      - "5001:5001"
    restart: always
    # overrides the command in the Dockerfile if needed
    # command: gunicorn src.main:app -w 2 --threads 2 -b 0.0.0.0:5001
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ip-addr-challenge
